info:
    serviceLinks:
        api-doc: "${route.name}/docs/index.html"
    dependencies:
        skatteetaten: "skatteetaten"

spring:
    profiles:
        active: local

logging:
    level:
      ske.aurora: INFO
      no.skatteetaten: INFO
      org:
        springframework: WARN
        apache.catalina: WARN
        hibernate: WARN

---
spring:
  profiles: local
  datasource:
    url: "jdbc:oracle:thin:@uil0map-drivein-db02:1521/dbhotel"
    username: "PTEEYLLKRGKGWONIHSAPJBCAQSYIGV"
    password: "a17gQoC3GI14RJaMdu7CInjzjPO4sX"


management:
    server.port: 8081


logging:
    pattern:
      console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"

